version : '3.8'

services:
  php:
    build: .
    container_name : php
    ports:
      - 80:80

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports: 
      - 8080:80
    restart: always
    environment:
      PMA_HOST: 34.129.197.10
